version: '3.4'
services:
  # back-end api built with golang
  golang:
    restart: always
    build: 
      context: golang
      dockerfile: server.Dockerfile
      target: prod
    ports:
      - "5000:5000"
    volumes:
      - ./rubyx-data:/rubyx-data
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy

  # front-end built with react
  react:
    restart: always
    build: 
      context: dashboard
      target: prod
    ports:
      - "3000:3000"

  postgres:
    build: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - ./golang/sql/schema:/docker-entrypoint-initdb.d/schema