version: '3.4'
services:
  # back-end api built with golang
  golang:
    restart: always
    build: 
      context: golang
      dockerfile: server.Dockerfile
      target: prod
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - postgres

  # front-end built with react
  react:
    restart: always
    build: 
      context: dashboard
      target: prod
    ports:
      - "3000:3000"

  postgres:
    build: postgres
    volumes:
      - ./golang/sql/schema:/docker-entrypoint-initdb.d/schema