version: '3.4'
services:
  # API server
  golang-prod:
    build:
      context: golang
      dockerfile: server.Dockerfile
      target: prod
    # image: registry-host:5000/rubyx/golang-prod:${GITHUB_SHA}
  
  # worker
  worker-prod:
    build:
      context: golang
      dockerfile: worker.Dockerfile
      target: prod
    # image: registry-host:5000/rubyx/worker-prod:${GITHUB_SHA}

  # front-end built with react
  react-prod:
    build:
      context: dashboard
      target: prod
    # image: registry-host:5000/rubyx/react-prod:${GITHUB_SHA}
    volumes:
    - ./.npm:/.npm
