version: '3.4'
services:
  # back-end api built with golang
  golang:
    build: 
      context: golang
      dockerfile: server.Dockerfile
      target: dev
    volumes:
      - ./golang:/app
      - ./rubyx-data:/rubyx-data
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy

  # front-end built with react
  react:
    stdin_open: true
    build:
      context: dashboard
      target: dev
    volumes:
      - ./dashboard:/root
    ports:
      - "3000:3000"

  # postgres is our primary data store
  postgres:
    build: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - ./golang/sql/schema:/docker-entrypoint-initdb.d/schema

  # nginx is used for ssl termination
  nginx:
    build: 
      context: nginx
      target: dev
    ports:
      - "443:443"
    depends_on:
      - react
      - golang
